== Heimdall - Environment and Release Management

He is the all-seeing and all-hearing guardian sentry of Asgard, he stands on the rainbow bridge, Bifrost and stands
watch for any attacks to Asgard.

== Build Status

image:https://travis-ci.org/willis7/Heimdall.svg?branch=master[Build Status,link=https://travis-ci.org/willis7/Heimdall]

== Problem

Release and Environment management is hard. As data centres grow, and the number of applications you support increases,
so does the headache of tracking how resources are used. In an ideal world environments would be an endless resource and
we could have as many as we liked, but the reality is these are finite and we should manage them accordingly.

== Solution

The purpose of Heimdall is to solve, or at least help reduce the problem described above. By tracking the resources you
have, and knowing how long they will be in use can significantly reduce the amount of resource contention.

== Built with

* Grails 2.4.4
* Java 1.7.0_71

== Run Heimdall

Run Heimdall by running:

[source]
----
grailsw run-app
----

== Contribute

* Issue Tracker: https://github.com/willis7/Heimdall/issues[https://github.com/willis7/Heimdall/issues]
* Source Code: https://github.com/willis7/Heimdall[https://github.com/willis7/Heimdall]

== Support

If you are having issues, please let us know.

== License

The project is licensed under the BSD license.